// the first start with pipeline { set up agent and stages inside pipeline }
pipeline {

    // any คือ ใช้ executor ใด ๆ ก็ได้
    agent any

    // stages as working Flows tell Pipeline what gonna do
    stages {
                stage('Before initial check software installed') {
                    steps {
                          sh 'java -version'
                          sh 'mvn -version'
                          sh 'git --version'
                    }
                }

                stage('Checkout git repo') {
                    steps {
                        // Checks out the source code from your Git repository. *** Note, by default it will pull repo to C:\ProgramData\Jenkins\.jenkins\workspace\...
                        git branch: 'ttknp', url: 'https://github.com/Thitikorn-Nupan/jenskins-and-spring-boot-apply-multiple-modules-crud-mysql.git'
                    }
                }


                stage('Build') {
                    steps {
                        // Builds the Spring Boot application using maven
                        sh "mvn clean install -X -DskipTests"
                    }
                }
            }
    }
